export const TENANT_SCOPED_TABLES = [
  {
    table: 'tenants',
    schema: 'public',
    description: 'Root tenant entity - each row IS the tenant',
    reason: 'Primary tenant entity - tenant_id is the primary key',
    hasNotNullTenantId: true,
    hasTenantFk: false,
    hasRls: false,
  },
  {
    table: 'users',
    schema: 'public',
    description: 'Tenant-scoped user accounts',
    reason: 'Users belong to tenants via tenant_id FK to public.tenants',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'sessions',
    schema: 'auth',
    description: 'Authentication sessions scoped to tenants',
    reason: 'Sessions are tied to users who belong to tenants',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
    compositeForeignKeys: [
      {
        columns: ['tenant_id', 'user_id'],
        references: ['public.users.tenant_id', 'public.users.user_id'],
      },
    ],
  },
  {
    table: 'roles',
    schema: 'auth',
    description: 'Tenant-specific RBAC roles',
    reason: 'Roles are tenant-scoped for RBAC isolation',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'user_roles',
    schema: 'auth',
    description: 'User-role assignments scoped to tenants',
    reason: 'User role bindings must respect tenant boundaries',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
    compositeForeignKeys: [
      {
        columns: ['tenant_id', 'user_id'],
        references: ['public.users.tenant_id', 'public.users.user_id'],
      },
      {
        columns: ['tenant_id', 'role_id'],
        references: ['auth.roles.tenant_id', 'auth.roles.id'],
      },
      {
        columns: ['tenant_id', 'assigned_by'],
        references: ['public.users.tenant_id', 'public.users.user_id'],
      },
    ],
  },
  {
    table: 'role_permissions',
    schema: 'auth',
    description: 'Role-permission bindings scoped to tenants',
    reason: 'Permissions are assigned to tenant-scoped roles via FK to auth.roles',
    hasNotNullTenantId: false,
    hasTenantFk: false,
    hasRls: true,
    note: 'Tenant isolation via FK to auth.roles which is already tenant-scoped',
  },
  {
    table: 'sso_connections',
    schema: 'auth',
    description: 'Tenant SSO configuration',
    reason: 'SSO connections are per-tenant for IdP isolation',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'user_profiles',
    schema: 'auth',
    description: 'User profile preferences scoped to tenants',
    reason: 'Profiles contain tenant-specific settings and preferences',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
    compositeForeignKeys: [
      {
        columns: ['tenant_id', 'user_id'],
        references: ['public.users.tenant_id', 'public.users.user_id'],
      },
    ],
  },
  {
    table: 'webauthn_credentials',
    schema: 'auth',
    description: 'WebAuthn credentials scoped to tenants',
    reason: 'WebAuthn credentials are tied to users who belong to tenants',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'mfa_credentials',
    schema: 'auth',
    description: 'MFA credentials scoped to tenants',
    reason: 'MFA credentials are tied to users who belong to tenants',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'backup_codes',
    schema: 'auth',
    description: 'Backup codes scoped to tenants',
    reason: 'Backup codes are tied to users who belong to tenants',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'prompt_templates',
    schema: 'ai',
    description: 'Versioned AI prompt templates scoped to tenants',
    reason: 'Prompt templates store tenant-owned AI generation rules and metadata',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'game_sessions',
    schema: 'public',
    description: 'Tenant-scoped game sessions',
    reason: 'Game sessions are tied to users who belong to tenants',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'game_events',
    schema: 'public',
    description: 'Tenant-scoped game events for event sourcing',
    reason: 'Game events are tied to game sessions which belong to tenants',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'game_state_snapshots',
    schema: 'public',
    description: 'Tenant-scoped game state snapshots',
    reason: 'State snapshots are tied to game sessions which belong to tenants',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'economy_transactions',
    schema: 'public',
    description: 'Tenant-scoped economy transactions',
    reason: 'Economy transactions track currency changes per tenant',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'email_templates',
    schema: 'content',
    description: 'Tenant-scoped email templates',
    reason: 'Email templates are per-tenant content items',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'scenarios',
    schema: 'content',
    description: 'Tenant-scoped training scenarios',
    reason: 'Scenarios are per-tenant content items',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'scenario_beats',
    schema: 'content',
    description: 'Tenant-scoped scenario beats',
    reason: 'Scenario beats are tied to scenarios which belong to tenants',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'document_templates',
    schema: 'content',
    description: 'Tenant-scoped document templates',
    reason: 'Document templates are per-tenant content items',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'localized_content',
    schema: 'content',
    description: 'Tenant-scoped localized content',
    reason: 'Localized content is per-tenant',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'ai_generation_log',
    schema: 'content',
    description: 'Tenant-scoped AI generation audit log',
    reason: 'AI generation logs track per-tenant AI usage',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'factions',
    schema: 'content',
    description: 'Tenant-scoped faction definitions',
    reason: 'Factions are per-tenant narrative elements',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'faction_relations',
    schema: 'content',
    description: 'Tenant-scoped faction relations',
    reason: 'Faction relations track per-tenant player-faction interactions',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'narrative_events',
    schema: 'content',
    description: 'Tenant-scoped narrative events',
    reason: 'Narrative events are per-tenant player experiences',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'morpheus_messages',
    schema: 'content',
    description: 'Tenant-scoped Morpheus coaching messages',
    reason: 'Coaching messages are per-tenant configuration',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'player_narrative_state',
    schema: 'content',
    description: 'Tenant-scoped player narrative progress',
    reason: 'Player narrative state tracks per-tenant player progress',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'events',
    schema: 'analytics',
    description: 'Tenant-scoped analytics events',
    reason: 'Analytics events are per-tenant data points',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'player_profiles',
    schema: 'analytics',
    description: 'Tenant-scoped player profiles',
    reason: 'Player profiles track per-tenant player statistics',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'dead_letter_queue',
    schema: 'analytics',
    description: 'Tenant-scoped dead letter queue',
    reason: 'DLQ entries are per-tenant for failed event processing',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'metrics',
    schema: 'analytics',
    description: 'Analytics metrics (tenant_id is nullable for system metrics)',
    reason: 'Metrics can be per-tenant or system-wide',
    hasNotNullTenantId: false,
    hasTenantFk: false,
    hasRls: true,
    note: 'tenant_id is nullable; RLS allows NULL for system metrics',
  },
  {
    table: 'records',
    schema: 'idempotency',
    description: 'Tenant-scoped idempotency records',
    reason: 'Idempotency keys prevent duplicate requests per tenant',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'certificates',
    schema: 'training',
    description: 'Tenant-scoped training completion certificates',
    reason: 'Certificates are per-tenant compliance evidence',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'scim_tokens',
    schema: 'auth',
    description: 'SCIM bearer tokens for IdP authentication',
    reason: 'SCIM tokens are per-tenant for IdP provisioning',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'scim_groups',
    schema: 'auth',
    description: 'Persistent SCIM groups',
    reason: 'SCIM groups are tenant-scoped',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
  {
    table: 'scim_group_members',
    schema: 'auth',
    description: 'SCIM group membership mappings',
    reason: 'Group members inherit tenant scope from groups',
    hasNotNullTenantId: false,
    hasTenantFk: false,
    hasRls: true,
    note: 'Tenant isolation via FK to auth.scim_groups',
  },
  {
    table: 'scim_sync_logs',
    schema: 'auth',
    description: 'SCIM sync status tracking',
    reason: 'Sync logs are per-tenant',
    hasNotNullTenantId: true,
    hasTenantFk: true,
    hasRls: true,
  },
] as const;

export const GLOBAL_TABLES = [
  {
    table: 'permissions',
    schema: 'auth',
    description: 'Global permission definitions',
    reason: 'Permissions are system-wide definitions, not tenant-scoped',
    hasTenantId: false,
    note: 'Authorization uses permission strings, not tenant-bound resources',
  },
] as const;

export type TenantScopedTable = (typeof TENANT_SCOPED_TABLES)[number];
export type GlobalTable = (typeof GLOBAL_TABLES)[number];

export function isTenantScoped(schema: string, table: string): boolean {
  return TENANT_SCOPED_TABLES.some((t) => t.schema === schema && t.table === table);
}

export function isGlobalTable(schema: string, table: string): boolean {
  return GLOBAL_TABLES.some((t) => t.schema === schema && t.table === table);
}

export function getTablePolicy(
  schema: string,
  table: string,
): TenantScopedTable | GlobalTable | undefined {
  const tenantScoped = TENANT_SCOPED_TABLES.find((t) => t.schema === schema && t.table === table);
  if (tenantScoped) return tenantScoped;

  const global = GLOBAL_TABLES.find((t) => t.schema === schema && t.table === table);
  return global;
}
