// This file is auto-generated by scripts/generate-json-schemas.ts. Do not edit.

export const loginJsonSchema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      format: 'email',
    },
    password: {
      type: 'string',
      minLength: 8,
      maxLength: 128,
    },
  },
  required: ['email', 'password'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const registerJsonSchema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      format: 'email',
    },
    password: {
      type: 'string',
      minLength: 12,
      maxLength: 128,
    },
    displayName: {
      type: 'string',
      minLength: 2,
      maxLength: 64,
    },
  },
  required: ['email', 'password', 'displayName'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const refreshTokenJsonSchema = {
  type: 'object',
  properties: {
    refreshToken: {
      type: 'string',
      minLength: 1,
    },
  },
  required: ['refreshToken'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const loginResponseJsonSchema = {
  type: 'object',
  properties: {
    user: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          format: 'uuid',
        },
        email: {
          type: 'string',
          format: 'email',
        },
        displayName: {
          type: 'string',
        },
        tenantId: {
          type: 'string',
          format: 'uuid',
        },
        role: {
          type: 'string',
        },
        isActive: {
          type: 'boolean',
        },
      },
      required: ['id', 'email', 'displayName', 'tenantId', 'role', 'isActive'],
      additionalProperties: false,
    },
    accessToken: {
      type: 'string',
    },
  },
  required: ['user', 'accessToken'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const registerResponseJsonSchema = {
  type: 'object',
  properties: {
    user: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          format: 'uuid',
        },
        email: {
          type: 'string',
          format: 'email',
        },
        displayName: {
          type: 'string',
        },
        tenantId: {
          type: 'string',
          format: 'uuid',
        },
        role: {
          type: 'string',
        },
        isActive: {
          type: 'boolean',
        },
      },
      required: ['id', 'email', 'displayName', 'tenantId', 'role', 'isActive'],
      additionalProperties: false,
    },
    accessToken: {
      type: 'string',
    },
  },
  required: ['user', 'accessToken'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const refreshResponseJsonSchema = {
  type: 'object',
  properties: {
    accessToken: {
      type: 'string',
    },
  },
  required: ['accessToken'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const userJsonSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    email: {
      type: 'string',
      format: 'email',
    },
    displayName: {
      type: 'string',
    },
    tenantId: {
      type: 'string',
      format: 'uuid',
    },
    role: {
      type: 'string',
    },
    isActive: {
      type: 'boolean',
    },
  },
  required: ['id', 'email', 'displayName', 'tenantId', 'role', 'isActive'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const logoutResponseJsonSchema = {
  type: 'object',
  properties: {
    success: {
      type: 'boolean',
    },
  },
  required: ['success'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const profileJsonSchema = {
  type: 'object',
  properties: {
    profileId: {
      type: 'string',
      format: 'uuid',
    },
    tenantId: {
      type: 'string',
      format: 'uuid',
    },
    userId: {
      type: 'string',
      format: 'uuid',
    },
    locale: {
      type: 'string',
      maxLength: 10,
    },
    timezone: {
      type: 'string',
      maxLength: 64,
    },
    accessibilitySettings: {
      type: 'object',
      additionalProperties: {},
    },
    notificationSettings: {
      type: 'object',
      additionalProperties: {},
    },
  },
  required: [
    'profileId',
    'tenantId',
    'userId',
    'locale',
    'timezone',
    'accessibilitySettings',
    'notificationSettings',
  ],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const updateProfileJsonSchema = {
  type: 'object',
  properties: {
    locale: {
      type: 'string',
      maxLength: 10,
    },
    timezone: {
      type: 'string',
      maxLength: 64,
    },
    accessibilitySettings: {
      type: 'object',
      additionalProperties: {},
    },
    notificationSettings: {
      type: 'object',
      additionalProperties: {},
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const meResponseJsonSchema = {
  type: 'object',
  properties: {
    user: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          format: 'uuid',
        },
        email: {
          type: 'string',
          format: 'email',
        },
        displayName: {
          type: 'string',
        },
        tenantId: {
          type: 'string',
          format: 'uuid',
        },
        role: {
          type: 'string',
        },
        isActive: {
          type: 'boolean',
        },
      },
      required: ['id', 'email', 'displayName', 'tenantId', 'role', 'isActive'],
      additionalProperties: false,
    },
    profile: {
      type: 'object',
      properties: {
        profileId: {
          type: 'string',
          format: 'uuid',
        },
        tenantId: {
          type: 'string',
          format: 'uuid',
        },
        userId: {
          type: 'string',
          format: 'uuid',
        },
        locale: {
          type: 'string',
          maxLength: 10,
        },
        timezone: {
          type: 'string',
          maxLength: 64,
        },
        accessibilitySettings: {
          type: 'object',
          additionalProperties: {},
        },
        notificationSettings: {
          type: 'object',
          additionalProperties: {},
        },
      },
      required: [
        'profileId',
        'tenantId',
        'userId',
        'locale',
        'timezone',
        'accessibilitySettings',
        'notificationSettings',
      ],
      additionalProperties: false,
    },
  },
  required: ['user'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const paginationJsonSchema = {
  type: 'object',
  properties: {
    page: {
      type: 'integer',
      exclusiveMinimum: 0,
      default: 1,
    },
    limit: {
      type: 'integer',
      minimum: 1,
      maximum: 100,
      default: 20,
    },
    sortBy: {
      type: 'string',
    },
    sortOrder: {
      type: 'string',
      enum: ['asc', 'desc'],
      default: 'desc',
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const dateRangeJsonSchema = {
  type: 'object',
  properties: {
    start: {
      type: 'string',
      format: 'date-time',
    },
    end: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: ['start', 'end'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const healthQueryJsonSchema = {
  type: 'object',
  properties: {
    probe: {
      type: 'string',
      enum: ['liveness', 'readiness'],
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const healthResponseJsonSchema = {
  type: 'object',
  properties: {
    status: {
      type: 'string',
      const: 'ok',
    },
  },
  required: ['status'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const readinessResponseJsonSchema = {
  type: 'object',
  properties: {
    status: {
      type: 'string',
      enum: ['ok', 'degraded'],
    },
    checks: {
      type: 'object',
      properties: {
        database: {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
            },
            message: {
              type: 'string',
            },
          },
          required: ['ok', 'message'],
          additionalProperties: false,
        },
        redis: {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
            },
            message: {
              type: 'string',
            },
          },
          required: ['ok', 'message'],
          additionalProperties: false,
        },
      },
      required: ['database', 'redis'],
      additionalProperties: false,
    },
  },
  required: ['status', 'checks'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const apiErrorJsonSchema = {
  type: 'object',
  properties: {
    code: {
      type: 'string',
    },
    message: {
      type: 'string',
    },
    details: {
      type: 'object',
      additionalProperties: {},
    },
    requestId: {
      type: 'string',
    },
  },
  required: ['code', 'message'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const apiErrorEnvelopeJsonSchema = {
  type: 'object',
  properties: {
    success: {
      type: 'boolean',
      const: false,
    },
    error: {
      type: 'object',
      properties: {
        code: {
          type: 'string',
        },
        message: {
          type: 'string',
        },
        details: {
          type: 'object',
          additionalProperties: {},
        },
        requestId: {
          type: 'string',
        },
      },
      required: ['code', 'message'],
      additionalProperties: false,
    },
  },
  required: ['success', 'error'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;
