// This file is auto-generated by scripts/generate-json-schemas.ts. Do not edit.

export const loginJsonSchema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      format: 'email',
    },
    password: {
      type: 'string',
      minLength: 8,
      maxLength: 128,
    },
  },
  required: ['email', 'password'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const registerJsonSchema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      format: 'email',
    },
    password: {
      type: 'string',
      minLength: 12,
      maxLength: 128,
    },
    displayName: {
      type: 'string',
      minLength: 2,
      maxLength: 64,
    },
  },
  required: ['email', 'password', 'displayName'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const refreshTokenJsonSchema = {
  type: 'object',
  properties: {
    refreshToken: {
      type: 'string',
      minLength: 1,
    },
  },
  required: ['refreshToken'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const loginResponseJsonSchema = {
  type: 'object',
  properties: {
    user: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          format: 'uuid',
        },
        email: {
          type: 'string',
          format: 'email',
        },
        displayName: {
          type: 'string',
        },
        tenantId: {
          type: 'string',
          format: 'uuid',
        },
        role: {
          type: 'string',
        },
        isActive: {
          type: 'boolean',
        },
      },
      required: ['id', 'email', 'displayName', 'tenantId', 'role', 'isActive'],
      additionalProperties: false,
    },
    accessToken: {
      type: 'string',
    },
  },
  required: ['user', 'accessToken'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const registerResponseJsonSchema = {
  type: 'object',
  properties: {
    user: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          format: 'uuid',
        },
        email: {
          type: 'string',
          format: 'email',
        },
        displayName: {
          type: 'string',
        },
        tenantId: {
          type: 'string',
          format: 'uuid',
        },
        role: {
          type: 'string',
        },
        isActive: {
          type: 'boolean',
        },
      },
      required: ['id', 'email', 'displayName', 'tenantId', 'role', 'isActive'],
      additionalProperties: false,
    },
    accessToken: {
      type: 'string',
    },
  },
  required: ['user', 'accessToken'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const refreshResponseJsonSchema = {
  type: 'object',
  properties: {
    accessToken: {
      type: 'string',
    },
  },
  required: ['accessToken'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const userJsonSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    email: {
      type: 'string',
      format: 'email',
    },
    displayName: {
      type: 'string',
    },
    tenantId: {
      type: 'string',
      format: 'uuid',
    },
    role: {
      type: 'string',
    },
    isActive: {
      type: 'boolean',
    },
  },
  required: ['id', 'email', 'displayName', 'tenantId', 'role', 'isActive'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const logoutResponseJsonSchema = {
  type: 'object',
  properties: {
    success: {
      type: 'boolean',
    },
  },
  required: ['success'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const profileJsonSchema = {
  type: 'object',
  properties: {
    profileId: {
      type: 'string',
      format: 'uuid',
    },
    tenantId: {
      type: 'string',
      format: 'uuid',
    },
    userId: {
      type: 'string',
      format: 'uuid',
    },
    locale: {
      type: 'string',
      maxLength: 10,
    },
    timezone: {
      type: 'string',
      maxLength: 64,
    },
    preferences: {
      type: 'object',
      properties: {
        themePreferences: {
          type: 'object',
          properties: {
            theme: {
              type: 'string',
              enum: ['green', 'amber', 'high-contrast', 'enterprise'],
            },
            enableTerminalEffects: {
              type: 'boolean',
            },
            effects: {
              type: 'object',
              properties: {
                scanlines: {
                  type: 'boolean',
                },
                curvature: {
                  type: 'boolean',
                },
                glow: {
                  type: 'boolean',
                },
                noise: {
                  type: 'boolean',
                },
                vignette: {
                  type: 'boolean',
                },
              },
              required: ['scanlines', 'curvature', 'glow', 'noise', 'vignette'],
              additionalProperties: false,
            },
            fontSize: {
              type: 'number',
              minimum: 12,
              maximum: 32,
            },
          },
          additionalProperties: false,
        },
        accessibilityPreferences: {
          type: 'object',
          properties: {
            reducedMotion: {
              type: 'boolean',
            },
            highContrast: {
              type: 'boolean',
            },
            fontSize: {
              type: 'number',
              minimum: 12,
              maximum: 32,
            },
          },
          additionalProperties: false,
        },
      },
      additionalProperties: false,
    },
    policyLockedPreferences: {
      type: 'object',
      properties: {
        theme: {
          type: 'boolean',
        },
        enableTerminalEffects: {
          type: 'boolean',
        },
        effects: {
          type: 'object',
          additionalProperties: {
            type: 'boolean',
          },
        },
        fontSize: {
          type: 'boolean',
        },
        reducedMotion: {
          type: 'boolean',
        },
        highContrast: {
          type: 'boolean',
        },
      },
      additionalProperties: false,
    },
    accessibilitySettings: {
      type: 'object',
      additionalProperties: {},
    },
    notificationSettings: {
      type: 'object',
      additionalProperties: {},
    },
  },
  required: [
    'profileId',
    'tenantId',
    'userId',
    'locale',
    'timezone',
    'accessibilitySettings',
    'notificationSettings',
  ],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const updateProfileJsonSchema = {
  type: 'object',
  properties: {
    locale: {
      type: 'string',
      maxLength: 10,
    },
    timezone: {
      type: 'string',
      maxLength: 64,
    },
    preferences: {
      type: 'object',
      properties: {
        themePreferences: {
          type: 'object',
          properties: {
            theme: {
              type: 'string',
              enum: ['green', 'amber', 'high-contrast', 'enterprise'],
            },
            enableTerminalEffects: {
              type: 'boolean',
            },
            effects: {
              type: 'object',
              properties: {
                scanlines: {
                  type: 'boolean',
                },
                curvature: {
                  type: 'boolean',
                },
                glow: {
                  type: 'boolean',
                },
                noise: {
                  type: 'boolean',
                },
                vignette: {
                  type: 'boolean',
                },
              },
              required: ['scanlines', 'curvature', 'glow', 'noise', 'vignette'],
              additionalProperties: false,
            },
            fontSize: {
              type: 'number',
              minimum: 12,
              maximum: 32,
            },
          },
          additionalProperties: false,
        },
        accessibilityPreferences: {
          type: 'object',
          properties: {
            reducedMotion: {
              type: 'boolean',
            },
            highContrast: {
              type: 'boolean',
            },
            fontSize: {
              type: 'number',
              minimum: 12,
              maximum: 32,
            },
          },
          additionalProperties: false,
        },
      },
      additionalProperties: false,
    },
    accessibilitySettings: {
      type: 'object',
      additionalProperties: {},
    },
    notificationSettings: {
      type: 'object',
      additionalProperties: {},
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const meResponseJsonSchema = {
  type: 'object',
  properties: {
    user: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          format: 'uuid',
        },
        email: {
          type: 'string',
          format: 'email',
        },
        displayName: {
          type: 'string',
        },
        tenantId: {
          type: 'string',
          format: 'uuid',
        },
        role: {
          type: 'string',
        },
        isActive: {
          type: 'boolean',
        },
      },
      required: ['id', 'email', 'displayName', 'tenantId', 'role', 'isActive'],
      additionalProperties: false,
    },
    profile: {
      type: 'object',
      properties: {
        profileId: {
          type: 'string',
          format: 'uuid',
        },
        tenantId: {
          type: 'string',
          format: 'uuid',
        },
        userId: {
          type: 'string',
          format: 'uuid',
        },
        locale: {
          type: 'string',
          maxLength: 10,
        },
        timezone: {
          type: 'string',
          maxLength: 64,
        },
        preferences: {
          type: 'object',
          properties: {
            themePreferences: {
              type: 'object',
              properties: {
                theme: {
                  type: 'string',
                  enum: ['green', 'amber', 'high-contrast', 'enterprise'],
                },
                enableTerminalEffects: {
                  type: 'boolean',
                },
                effects: {
                  type: 'object',
                  properties: {
                    scanlines: {
                      type: 'boolean',
                    },
                    curvature: {
                      type: 'boolean',
                    },
                    glow: {
                      type: 'boolean',
                    },
                    noise: {
                      type: 'boolean',
                    },
                    vignette: {
                      type: 'boolean',
                    },
                  },
                  required: ['scanlines', 'curvature', 'glow', 'noise', 'vignette'],
                  additionalProperties: false,
                },
                fontSize: {
                  type: 'number',
                  minimum: 12,
                  maximum: 32,
                },
              },
              additionalProperties: false,
            },
            accessibilityPreferences: {
              type: 'object',
              properties: {
                reducedMotion: {
                  type: 'boolean',
                },
                highContrast: {
                  type: 'boolean',
                },
                fontSize: {
                  type: 'number',
                  minimum: 12,
                  maximum: 32,
                },
              },
              additionalProperties: false,
            },
          },
          additionalProperties: false,
        },
        policyLockedPreferences: {
          type: 'object',
          properties: {
            theme: {
              type: 'boolean',
            },
            enableTerminalEffects: {
              type: 'boolean',
            },
            effects: {
              type: 'object',
              additionalProperties: {
                type: 'boolean',
              },
            },
            fontSize: {
              type: 'boolean',
            },
            reducedMotion: {
              type: 'boolean',
            },
            highContrast: {
              type: 'boolean',
            },
          },
          additionalProperties: false,
        },
        accessibilitySettings: {
          type: 'object',
          additionalProperties: {},
        },
        notificationSettings: {
          type: 'object',
          additionalProperties: {},
        },
      },
      required: [
        'profileId',
        'tenantId',
        'userId',
        'locale',
        'timezone',
        'accessibilitySettings',
        'notificationSettings',
      ],
      additionalProperties: false,
    },
    effectivePreferences: {
      type: 'object',
      properties: {
        themePreferences: {
          type: 'object',
          properties: {
            theme: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    value: {},
                    source: {
                      type: 'string',
                      enum: ['policy', 'server', 'local', 'os', 'default'],
                    },
                  },
                  required: ['source'],
                  additionalProperties: false,
                },
                {
                  type: 'null',
                },
              ],
            },
            enableTerminalEffects: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    value: {},
                    source: {
                      type: 'string',
                      enum: ['policy', 'server', 'local', 'os', 'default'],
                    },
                  },
                  required: ['source'],
                  additionalProperties: false,
                },
                {
                  type: 'null',
                },
              ],
            },
            effects: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    value: {},
                    source: {
                      type: 'string',
                      enum: ['policy', 'server', 'local', 'os', 'default'],
                    },
                  },
                  required: ['source'],
                  additionalProperties: false,
                },
                {
                  type: 'null',
                },
              ],
            },
            fontSize: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    value: {},
                    source: {
                      type: 'string',
                      enum: ['policy', 'server', 'local', 'os', 'default'],
                    },
                  },
                  required: ['source'],
                  additionalProperties: false,
                },
                {
                  type: 'null',
                },
              ],
            },
          },
          required: ['theme', 'enableTerminalEffects', 'effects', 'fontSize'],
          additionalProperties: false,
        },
        accessibilityPreferences: {
          type: 'object',
          properties: {
            reducedMotion: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    value: {},
                    source: {
                      type: 'string',
                      enum: ['policy', 'server', 'local', 'os', 'default'],
                    },
                  },
                  required: ['source'],
                  additionalProperties: false,
                },
                {
                  type: 'null',
                },
              ],
            },
            highContrast: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    value: {},
                    source: {
                      type: 'string',
                      enum: ['policy', 'server', 'local', 'os', 'default'],
                    },
                  },
                  required: ['source'],
                  additionalProperties: false,
                },
                {
                  type: 'null',
                },
              ],
            },
            fontSize: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    value: {},
                    source: {
                      type: 'string',
                      enum: ['policy', 'server', 'local', 'os', 'default'],
                    },
                  },
                  required: ['source'],
                  additionalProperties: false,
                },
                {
                  type: 'null',
                },
              ],
            },
          },
          required: ['reducedMotion', 'highContrast', 'fontSize'],
          additionalProperties: false,
        },
      },
      additionalProperties: false,
    },
  },
  required: ['user'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const paginationJsonSchema = {
  type: 'object',
  properties: {
    page: {
      type: 'integer',
      exclusiveMinimum: 0,
      default: 1,
    },
    limit: {
      type: 'integer',
      minimum: 1,
      maximum: 100,
      default: 20,
    },
    sortBy: {
      type: 'string',
    },
    sortOrder: {
      type: 'string',
      enum: ['asc', 'desc'],
      default: 'desc',
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const cursorPaginationJsonSchema = {
  type: 'object',
  properties: {
    cursor: {
      type: 'string',
    },
    limit: {
      type: 'integer',
      minimum: 1,
      maximum: 100,
      default: 20,
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const cursorPaginationMetaJsonSchema = {
  type: 'object',
  properties: {
    hasMore: {
      type: 'boolean',
    },
    nextCursor: {
      type: ['string', 'null'],
    },
    total: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  required: ['hasMore', 'nextCursor'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const dateRangeJsonSchema = {
  type: 'object',
  properties: {
    start: {
      type: 'string',
      format: 'date-time',
    },
    end: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: ['start', 'end'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const healthQueryJsonSchema = {
  type: 'object',
  properties: {
    probe: {
      type: 'string',
      enum: ['liveness', 'readiness'],
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const healthResponseJsonSchema = {
  type: 'object',
  properties: {
    status: {
      type: 'string',
      const: 'ok',
    },
  },
  required: ['status'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const readinessResponseJsonSchema = {
  type: 'object',
  properties: {
    status: {
      type: 'string',
      enum: ['ok', 'degraded'],
    },
    checks: {
      type: 'object',
      properties: {
        database: {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
            },
            message: {
              type: 'string',
            },
          },
          required: ['ok', 'message'],
          additionalProperties: false,
        },
        redis: {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
            },
            message: {
              type: 'string',
            },
          },
          required: ['ok', 'message'],
          additionalProperties: false,
        },
      },
      required: ['database', 'redis'],
      additionalProperties: false,
    },
  },
  required: ['status', 'checks'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const apiErrorJsonSchema = {
  type: 'object',
  properties: {
    code: {
      type: 'string',
    },
    message: {
      type: 'string',
    },
    details: {
      type: 'object',
      additionalProperties: {},
    },
    requestId: {
      type: 'string',
    },
  },
  required: ['code', 'message'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const apiErrorEnvelopeJsonSchema = {
  type: 'object',
  properties: {
    success: {
      type: 'boolean',
      const: false,
    },
    error: {
      type: 'object',
      properties: {
        code: {
          type: 'string',
        },
        message: {
          type: 'string',
        },
        details: {
          type: 'object',
          additionalProperties: {},
        },
        requestId: {
          type: 'string',
        },
      },
      required: ['code', 'message'],
      additionalProperties: false,
    },
  },
  required: ['success', 'error'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const effectStateJsonSchema = {
  type: 'object',
  properties: {
    scanlines: {
      type: 'boolean',
    },
    curvature: {
      type: 'boolean',
    },
    glow: {
      type: 'boolean',
    },
    noise: {
      type: 'boolean',
    },
    vignette: {
      type: 'boolean',
    },
  },
  required: ['scanlines', 'curvature', 'glow', 'noise', 'vignette'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const themePreferencesJsonSchema = {
  type: 'object',
  properties: {
    theme: {
      type: 'string',
      enum: ['green', 'amber', 'high-contrast', 'enterprise'],
    },
    enableTerminalEffects: {
      type: 'boolean',
    },
    effects: {
      type: 'object',
      properties: {
        scanlines: {
          type: 'boolean',
        },
        curvature: {
          type: 'boolean',
        },
        glow: {
          type: 'boolean',
        },
        noise: {
          type: 'boolean',
        },
        vignette: {
          type: 'boolean',
        },
      },
      required: ['scanlines', 'curvature', 'glow', 'noise', 'vignette'],
      additionalProperties: false,
    },
    fontSize: {
      type: 'number',
      minimum: 12,
      maximum: 32,
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const accessibilityPreferencesJsonSchema = {
  type: 'object',
  properties: {
    reducedMotion: {
      type: 'boolean',
    },
    highContrast: {
      type: 'boolean',
    },
    fontSize: {
      type: 'number',
      minimum: 12,
      maximum: 32,
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const userPreferencesJsonSchema = {
  type: 'object',
  properties: {
    themePreferences: {
      type: 'object',
      properties: {
        theme: {
          type: 'string',
          enum: ['green', 'amber', 'high-contrast', 'enterprise'],
        },
        enableTerminalEffects: {
          type: 'boolean',
        },
        effects: {
          type: 'object',
          properties: {
            scanlines: {
              type: 'boolean',
            },
            curvature: {
              type: 'boolean',
            },
            glow: {
              type: 'boolean',
            },
            noise: {
              type: 'boolean',
            },
            vignette: {
              type: 'boolean',
            },
          },
          required: ['scanlines', 'curvature', 'glow', 'noise', 'vignette'],
          additionalProperties: false,
        },
        fontSize: {
          type: 'number',
          minimum: 12,
          maximum: 32,
        },
      },
      additionalProperties: false,
    },
    accessibilityPreferences: {
      type: 'object',
      properties: {
        reducedMotion: {
          type: 'boolean',
        },
        highContrast: {
          type: 'boolean',
        },
        fontSize: {
          type: 'number',
          minimum: 12,
          maximum: 32,
        },
      },
      additionalProperties: false,
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const preferenceSourceJsonSchema = {
  type: 'string',
  enum: ['policy', 'server', 'local', 'os', 'default'],
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const effectivePreferenceValueJsonSchema = {
  type: 'object',
  properties: {
    value: {},
    source: {
      type: 'string',
      enum: ['policy', 'server', 'local', 'os', 'default'],
    },
  },
  required: ['source'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const effectiveThemePreferencesJsonSchema = {
  type: 'object',
  properties: {
    theme: {
      anyOf: [
        {
          type: 'object',
          properties: {
            value: {},
            source: {
              type: 'string',
              enum: ['policy', 'server', 'local', 'os', 'default'],
            },
          },
          required: ['source'],
          additionalProperties: false,
        },
        {
          type: 'null',
        },
      ],
    },
    enableTerminalEffects: {
      anyOf: [
        {
          type: 'object',
          properties: {
            value: {},
            source: {
              type: 'string',
              enum: ['policy', 'server', 'local', 'os', 'default'],
            },
          },
          required: ['source'],
          additionalProperties: false,
        },
        {
          type: 'null',
        },
      ],
    },
    effects: {
      anyOf: [
        {
          type: 'object',
          properties: {
            value: {},
            source: {
              type: 'string',
              enum: ['policy', 'server', 'local', 'os', 'default'],
            },
          },
          required: ['source'],
          additionalProperties: false,
        },
        {
          type: 'null',
        },
      ],
    },
    fontSize: {
      anyOf: [
        {
          type: 'object',
          properties: {
            value: {},
            source: {
              type: 'string',
              enum: ['policy', 'server', 'local', 'os', 'default'],
            },
          },
          required: ['source'],
          additionalProperties: false,
        },
        {
          type: 'null',
        },
      ],
    },
  },
  required: ['theme', 'enableTerminalEffects', 'effects', 'fontSize'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const effectiveAccessibilityPreferencesJsonSchema = {
  type: 'object',
  properties: {
    reducedMotion: {
      anyOf: [
        {
          type: 'object',
          properties: {
            value: {},
            source: {
              type: 'string',
              enum: ['policy', 'server', 'local', 'os', 'default'],
            },
          },
          required: ['source'],
          additionalProperties: false,
        },
        {
          type: 'null',
        },
      ],
    },
    highContrast: {
      anyOf: [
        {
          type: 'object',
          properties: {
            value: {},
            source: {
              type: 'string',
              enum: ['policy', 'server', 'local', 'os', 'default'],
            },
          },
          required: ['source'],
          additionalProperties: false,
        },
        {
          type: 'null',
        },
      ],
    },
    fontSize: {
      anyOf: [
        {
          type: 'object',
          properties: {
            value: {},
            source: {
              type: 'string',
              enum: ['policy', 'server', 'local', 'os', 'default'],
            },
          },
          required: ['source'],
          additionalProperties: false,
        },
        {
          type: 'null',
        },
      ],
    },
  },
  required: ['reducedMotion', 'highContrast', 'fontSize'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const effectivePreferencesJsonSchema = {
  type: 'object',
  properties: {
    themePreferences: {
      type: 'object',
      properties: {
        theme: {
          anyOf: [
            {
              type: 'object',
              properties: {
                value: {},
                source: {
                  type: 'string',
                  enum: ['policy', 'server', 'local', 'os', 'default'],
                },
              },
              required: ['source'],
              additionalProperties: false,
            },
            {
              type: 'null',
            },
          ],
        },
        enableTerminalEffects: {
          anyOf: [
            {
              type: 'object',
              properties: {
                value: {},
                source: {
                  type: 'string',
                  enum: ['policy', 'server', 'local', 'os', 'default'],
                },
              },
              required: ['source'],
              additionalProperties: false,
            },
            {
              type: 'null',
            },
          ],
        },
        effects: {
          anyOf: [
            {
              type: 'object',
              properties: {
                value: {},
                source: {
                  type: 'string',
                  enum: ['policy', 'server', 'local', 'os', 'default'],
                },
              },
              required: ['source'],
              additionalProperties: false,
            },
            {
              type: 'null',
            },
          ],
        },
        fontSize: {
          anyOf: [
            {
              type: 'object',
              properties: {
                value: {},
                source: {
                  type: 'string',
                  enum: ['policy', 'server', 'local', 'os', 'default'],
                },
              },
              required: ['source'],
              additionalProperties: false,
            },
            {
              type: 'null',
            },
          ],
        },
      },
      required: ['theme', 'enableTerminalEffects', 'effects', 'fontSize'],
      additionalProperties: false,
    },
    accessibilityPreferences: {
      type: 'object',
      properties: {
        reducedMotion: {
          anyOf: [
            {
              type: 'object',
              properties: {
                value: {},
                source: {
                  type: 'string',
                  enum: ['policy', 'server', 'local', 'os', 'default'],
                },
              },
              required: ['source'],
              additionalProperties: false,
            },
            {
              type: 'null',
            },
          ],
        },
        highContrast: {
          anyOf: [
            {
              type: 'object',
              properties: {
                value: {},
                source: {
                  type: 'string',
                  enum: ['policy', 'server', 'local', 'os', 'default'],
                },
              },
              required: ['source'],
              additionalProperties: false,
            },
            {
              type: 'null',
            },
          ],
        },
        fontSize: {
          anyOf: [
            {
              type: 'object',
              properties: {
                value: {},
                source: {
                  type: 'string',
                  enum: ['policy', 'server', 'local', 'os', 'default'],
                },
              },
              required: ['source'],
              additionalProperties: false,
            },
            {
              type: 'null',
            },
          ],
        },
      },
      required: ['reducedMotion', 'highContrast', 'fontSize'],
      additionalProperties: false,
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const updatePreferencesJsonSchema = {
  type: 'object',
  properties: {
    themePreferences: {
      type: 'object',
      properties: {
        theme: {
          type: 'string',
          enum: ['green', 'amber', 'high-contrast', 'enterprise'],
        },
        enableTerminalEffects: {
          type: 'boolean',
        },
        effects: {
          type: 'object',
          properties: {
            scanlines: {
              type: 'boolean',
            },
            curvature: {
              type: 'boolean',
            },
            glow: {
              type: 'boolean',
            },
            noise: {
              type: 'boolean',
            },
            vignette: {
              type: 'boolean',
            },
          },
          required: ['scanlines', 'curvature', 'glow', 'noise', 'vignette'],
          additionalProperties: false,
        },
        fontSize: {
          type: 'number',
          minimum: 12,
          maximum: 32,
        },
      },
      additionalProperties: false,
    },
    accessibilityPreferences: {
      type: 'object',
      properties: {
        reducedMotion: {
          type: 'boolean',
        },
        highContrast: {
          type: 'boolean',
        },
        fontSize: {
          type: 'number',
          minimum: 12,
          maximum: 32,
        },
      },
      additionalProperties: false,
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const policyLockedPreferencesJsonSchema = {
  type: 'object',
  properties: {
    theme: {
      type: 'boolean',
    },
    enableTerminalEffects: {
      type: 'boolean',
    },
    effects: {
      type: 'object',
      additionalProperties: {
        type: 'boolean',
      },
    },
    fontSize: {
      type: 'boolean',
    },
    reducedMotion: {
      type: 'boolean',
    },
    highContrast: {
      type: 'boolean',
    },
  },
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const gameSessionBootstrapJsonSchema = {
  type: 'object',
  properties: {
    schemaVersion: {
      type: 'number',
      const: 1,
    },
    tenantId: {
      type: 'string',
      format: 'uuid',
    },
    sessionId: {
      type: 'string',
      format: 'uuid',
    },
    userId: {
      type: 'string',
      format: 'uuid',
    },
    day: {
      type: 'integer',
      minimum: 1,
      default: 1,
    },
    funds: {
      type: 'integer',
      minimum: 0,
      default: 1000,
    },
    clientCount: {
      type: 'integer',
      minimum: 0,
      default: 5,
    },
    threatLevel: {
      type: 'string',
      enum: ['low', 'medium', 'high'],
      default: 'low',
    },
    facilityLoadout: {
      type: 'object',
      properties: {
        defenseLevel: {
          type: 'integer',
          minimum: 1,
          maximum: 10,
          default: 1,
        },
        serverLevel: {
          type: 'integer',
          minimum: 1,
          maximum: 10,
          default: 1,
        },
        networkLevel: {
          type: 'integer',
          minimum: 1,
          maximum: 10,
          default: 1,
        },
      },
      additionalProperties: false,
      default: {
        defenseLevel: 1,
        serverLevel: 1,
        networkLevel: 1,
      },
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: ['schemaVersion', 'tenantId', 'sessionId', 'userId', 'createdAt', 'updatedAt'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const gameSessionBootstrapResponseJsonSchema = {
  type: 'object',
  properties: {
    data: {
      type: 'object',
      properties: {
        schemaVersion: {
          type: 'number',
          const: 1,
        },
        tenantId: {
          type: 'string',
          format: 'uuid',
        },
        sessionId: {
          type: 'string',
          format: 'uuid',
        },
        userId: {
          type: 'string',
          format: 'uuid',
        },
        day: {
          type: 'integer',
          minimum: 1,
          default: 1,
        },
        funds: {
          type: 'integer',
          minimum: 0,
          default: 1000,
        },
        clientCount: {
          type: 'integer',
          minimum: 0,
          default: 5,
        },
        threatLevel: {
          type: 'string',
          enum: ['low', 'medium', 'high'],
          default: 'low',
        },
        facilityLoadout: {
          type: 'object',
          properties: {
            defenseLevel: {
              type: 'integer',
              minimum: 1,
              maximum: 10,
              default: 1,
            },
            serverLevel: {
              type: 'integer',
              minimum: 1,
              maximum: 10,
              default: 1,
            },
            networkLevel: {
              type: 'integer',
              minimum: 1,
              maximum: 10,
              default: 1,
            },
          },
          additionalProperties: false,
          default: {
            defenseLevel: 1,
            serverLevel: 1,
            networkLevel: 1,
          },
        },
        createdAt: {
          type: 'string',
          format: 'date-time',
        },
        updatedAt: {
          type: 'string',
          format: 'date-time',
        },
      },
      required: ['schemaVersion', 'tenantId', 'sessionId', 'userId', 'createdAt', 'updatedAt'],
      additionalProperties: false,
    },
  },
  required: ['data'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const webauthnChallengeRequestJsonSchema = {
  type: 'object',
  properties: {
    challengeType: {
      type: 'string',
      enum: ['registration', 'verification'],
    },
  },
  required: ['challengeType'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const webauthnChallengeResponseJsonSchema = {
  type: 'object',
  properties: {
    challenge: {
      type: 'string',
    },
    rp: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
        },
        name: {
          type: 'string',
        },
      },
      required: ['id', 'name'],
      additionalProperties: false,
    },
    user: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
        },
        name: {
          type: 'string',
        },
        displayName: {
          type: 'string',
        },
      },
      required: ['id', 'name', 'displayName'],
      additionalProperties: false,
    },
    pubKeyCredParams: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          type: {
            type: 'string',
            const: 'public-key',
          },
          alg: {
            type: 'number',
          },
        },
        required: ['type', 'alg'],
        additionalProperties: false,
      },
    },
    timeout: {
      type: 'number',
    },
    excludeCredentials: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: {
            type: 'string',
          },
          type: {
            type: 'string',
            const: 'public-key',
          },
        },
        required: ['id', 'type'],
        additionalProperties: false,
      },
    },
    authenticatorSelection: {
      type: 'object',
      properties: {
        requireResidentKey: {
          type: 'boolean',
        },
        residentKey: {
          type: 'string',
          enum: ['discouraged', 'preferred', 'required'],
        },
        authenticatorAttachment: {
          type: 'string',
          enum: ['platform', 'cross-platform'],
        },
        userVerification: {
          type: 'string',
          enum: ['required', 'preferred', 'discouraged'],
        },
      },
      additionalProperties: false,
    },
    attestation: {
      type: 'string',
      enum: ['none', 'indirect', 'direct', 'enterprise'],
    },
    extensions: {
      type: 'object',
      additionalProperties: {},
    },
  },
  required: ['challenge', 'rp', 'user', 'pubKeyCredParams'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const webauthnRegistrationRequestJsonSchema = {
  type: 'object',
  properties: {
    credential: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
        },
        rawId: {
          type: 'string',
        },
        type: {
          type: 'string',
          const: 'public-key',
        },
        response: {
          type: 'object',
          properties: {
            clientDataJSON: {
              type: 'string',
            },
            attestationObject: {
              type: 'string',
            },
            transports: {
              type: 'array',
              items: {
                type: 'string',
                enum: ['usb', 'nfc', 'ble', 'internal'],
              },
            },
          },
          required: ['clientDataJSON', 'attestationObject'],
          additionalProperties: false,
        },
        clientExtensionResults: {
          type: 'object',
          additionalProperties: {},
        },
      },
      required: ['id', 'rawId', 'type', 'response'],
      additionalProperties: false,
    },
  },
  required: ['credential'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const webauthnVerificationRequestJsonSchema = {
  type: 'object',
  properties: {
    credential: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
        },
        rawId: {
          type: 'string',
        },
        type: {
          type: 'string',
          const: 'public-key',
        },
        response: {
          type: 'object',
          properties: {
            clientDataJSON: {
              type: 'string',
            },
            authenticatorData: {
              type: 'string',
            },
            signature: {
              type: 'string',
            },
            userHandle: {
              type: 'string',
            },
          },
          required: ['clientDataJSON', 'authenticatorData', 'signature'],
          additionalProperties: false,
        },
        clientExtensionResults: {
          type: 'object',
          additionalProperties: {},
        },
      },
      required: ['id', 'rawId', 'type', 'response'],
      additionalProperties: false,
    },
    challengeId: {
      type: 'string',
      format: 'uuid',
    },
  },
  required: ['credential', 'challengeId'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const webauthnCredentialsListResponseJsonSchema = {
  type: 'object',
  properties: {
    credentials: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: {
            type: 'string',
            format: 'uuid',
          },
          credentialId: {
            type: 'string',
          },
          transports: {
            type: 'array',
            items: {
              type: 'string',
              enum: ['usb', 'nfc', 'ble', 'internal'],
            },
          },
          createdAt: {
            type: 'string',
            format: 'date-time',
          },
        },
        required: ['id', 'credentialId', 'createdAt'],
        additionalProperties: false,
      },
    },
  },
  required: ['credentials'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const webauthnRegistrationResponseJsonSchema = {
  type: 'object',
  properties: {
    success: {
      type: 'boolean',
    },
    credentialId: {
      type: 'string',
      format: 'uuid',
    },
  },
  required: ['success', 'credentialId'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const webauthnVerificationResponseJsonSchema = {
  type: 'object',
  properties: {
    success: {
      type: 'boolean',
    },
    mfaVerifiedAt: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: ['success', 'mfaVerifiedAt'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const mfaStatusResponseJsonSchema = {
  type: 'object',
  properties: {
    mfaRequired: {
      type: 'boolean',
    },
    mfaVerified: {
      type: 'boolean',
    },
    method: {
      anyOf: [
        {
          type: 'string',
          enum: ['webauthn', 'totp', 'sms', 'email'],
        },
        {
          type: 'null',
        },
      ],
    },
    mfaVerifiedAt: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
    },
    hasCredentials: {
      type: 'boolean',
    },
  },
  required: ['mfaRequired', 'mfaVerified', 'method', 'mfaVerifiedAt', 'hasCredentials'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const mfaMethodJsonSchema = {
  type: 'string',
  enum: ['webauthn', 'totp', 'sms', 'email'],
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const mfaChallengeStateJsonSchema = {
  type: 'object',
  properties: {
    required: {
      type: 'boolean',
    },
    verified: {
      type: ['boolean', 'null'],
    },
    method: {
      anyOf: [
        {
          type: 'string',
          enum: ['webauthn', 'totp', 'sms', 'email'],
        },
        {
          type: 'null',
        },
      ],
    },
    expiresAt: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  required: ['required', 'verified', 'method', 'expiresAt'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;

export const webauthnCredentialJsonSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    credentialId: {
      type: 'string',
    },
    publicKey: {
      type: 'string',
    },
    counter: {
      type: 'number',
    },
    transports: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['usb', 'nfc', 'ble', 'internal'],
      },
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: ['id', 'credentialId', 'publicKey', 'counter', 'createdAt'],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#',
} as const;
