export const ErrorCodeCategory = {
  AUTH: 'AUTH',
  VALIDATION: 'VALIDATION',
  GAME: 'GAME',
  TENANT: 'TENANT',
  SYSTEM: 'SYSTEM',
} as const;

export type ErrorCodeCategory = (typeof ErrorCodeCategory)[keyof typeof ErrorCodeCategory];

export const ErrorCodes = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_STATE_INVALID: 'GAME_STATE_INVALID',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  TENANT_CONTEXT_INVALID: 'TENANT_CONTEXT_INVALID',
  SYSTEM_INTERNAL_ERROR: 'SYSTEM_INTERNAL_ERROR',
  SYSTEM_SERVICE_UNAVAILABLE: 'SYSTEM_SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
