export const SESSION_MACRO_STATES = {
  SESSION_INIT: 'SESSION_INIT',
  SESSION_ACTIVE: 'SESSION_ACTIVE',
  SESSION_PAUSED: 'SESSION_PAUSED',
  SESSION_BREACH_RECOVERY: 'SESSION_BREACH_RECOVERY',
  SESSION_COMPLETED: 'SESSION_COMPLETED',
  SESSION_ABANDONED: 'SESSION_ABANDONED',
} as const;

export type SessionMacroState = (typeof SESSION_MACRO_STATES)[keyof typeof SESSION_MACRO_STATES];

export const DAY_PHASES = {
  PHASE_DAY_START: 'PHASE_DAY_START',
  PHASE_EMAIL_INTAKE: 'PHASE_EMAIL_INTAKE',
  PHASE_TRIAGE: 'PHASE_TRIAGE',
  PHASE_VERIFICATION: 'PHASE_VERIFICATION',
  PHASE_DECISION: 'PHASE_DECISION',
  PHASE_CONSEQUENCES: 'PHASE_CONSEQUENCES',
  PHASE_THREAT_PROCESSING: 'PHASE_THREAT_PROCESSING',
  PHASE_INCIDENT_RESPONSE: 'PHASE_INCIDENT_RESPONSE',
  PHASE_RESOURCE_MANAGEMENT: 'PHASE_RESOURCE_MANAGEMENT',
  PHASE_UPGRADE: 'PHASE_UPGRADE',
  PHASE_DAY_END: 'PHASE_DAY_END',
} as const;

export type DayPhase = (typeof DAY_PHASES)[keyof typeof DAY_PHASES];

export const MACRO_STATE_TRANSITIONS: Record<SessionMacroState, SessionMacroState[]> = {
  [SESSION_MACRO_STATES.SESSION_INIT]: [SESSION_MACRO_STATES.SESSION_ACTIVE],
  [SESSION_MACRO_STATES.SESSION_ACTIVE]: [
    SESSION_MACRO_STATES.SESSION_PAUSED,
    SESSION_MACRO_STATES.SESSION_BREACH_RECOVERY,
    SESSION_MACRO_STATES.SESSION_COMPLETED,
    SESSION_MACRO_STATES.SESSION_ABANDONED,
  ],
  [SESSION_MACRO_STATES.SESSION_PAUSED]: [SESSION_MACRO_STATES.SESSION_ACTIVE],
  [SESSION_MACRO_STATES.SESSION_BREACH_RECOVERY]: [
    SESSION_MACRO_STATES.SESSION_ACTIVE,
    SESSION_MACRO_STATES.SESSION_COMPLETED,
  ],
  [SESSION_MACRO_STATES.SESSION_COMPLETED]: [],
  [SESSION_MACRO_STATES.SESSION_ABANDONED]: [],
};

export const PHASE_TRANSITIONS: Record<DayPhase, DayPhase[]> = {
  [DAY_PHASES.PHASE_DAY_START]: [DAY_PHASES.PHASE_EMAIL_INTAKE],
  [DAY_PHASES.PHASE_EMAIL_INTAKE]: [DAY_PHASES.PHASE_TRIAGE],
  [DAY_PHASES.PHASE_TRIAGE]: [DAY_PHASES.PHASE_VERIFICATION, DAY_PHASES.PHASE_DECISION],
  [DAY_PHASES.PHASE_VERIFICATION]: [DAY_PHASES.PHASE_TRIAGE],
  [DAY_PHASES.PHASE_DECISION]: [DAY_PHASES.PHASE_CONSEQUENCES],
  [DAY_PHASES.PHASE_CONSEQUENCES]: [DAY_PHASES.PHASE_THREAT_PROCESSING],
  [DAY_PHASES.PHASE_THREAT_PROCESSING]: [
    DAY_PHASES.PHASE_INCIDENT_RESPONSE,
    DAY_PHASES.PHASE_RESOURCE_MANAGEMENT,
  ],
  [DAY_PHASES.PHASE_INCIDENT_RESPONSE]: [DAY_PHASES.PHASE_RESOURCE_MANAGEMENT],
  [DAY_PHASES.PHASE_RESOURCE_MANAGEMENT]: [DAY_PHASES.PHASE_UPGRADE],
  [DAY_PHASES.PHASE_UPGRADE]: [DAY_PHASES.PHASE_DAY_END],
  [DAY_PHASES.PHASE_DAY_END]: [DAY_PHASES.PHASE_DAY_START],
};

export const PHASE_LEGAL_ACTIONS: Record<DayPhase, readonly string[]> = {
  [DAY_PHASES.PHASE_DAY_START]: ['ACK_DAY_START'],
  [DAY_PHASES.PHASE_EMAIL_INTAKE]: ['LOAD_INBOX'],
  [DAY_PHASES.PHASE_TRIAGE]: [
    'OPEN_EMAIL',
    'MARK_INDICATOR',
    'REQUEST_VERIFICATION',
    'SUBMIT_DECISION',
  ],
  [DAY_PHASES.PHASE_VERIFICATION]: ['OPEN_VERIFICATION', 'MARK_INDICATOR', 'CLOSE_VERIFICATION'],
  [DAY_PHASES.PHASE_DECISION]: ['SUBMIT_DECISION'],
  [DAY_PHASES.PHASE_CONSEQUENCES]: ['APPLY_CONSEQUENCES'],
  [DAY_PHASES.PHASE_THREAT_PROCESSING]: ['PROCESS_THREATS'],
  [DAY_PHASES.PHASE_INCIDENT_RESPONSE]: ['RESOLVE_INCIDENT'],
  [DAY_PHASES.PHASE_RESOURCE_MANAGEMENT]: ['ADJUST_RESOURCE'],
  [DAY_PHASES.PHASE_UPGRADE]: ['PURCHASE_UPGRADE'],
  [DAY_PHASES.PHASE_DAY_END]: ['ADVANCE_DAY'],
};

export const GAME_ACTIONS = {
  ACK_DAY_START: 'ACK_DAY_START',
  ADVANCE_DAY: 'ADVANCE_DAY',
  LOAD_INBOX: 'LOAD_INBOX',
  OPEN_EMAIL: 'OPEN_EMAIL',
  MARK_INDICATOR: 'MARK_INDICATOR',
  REQUEST_VERIFICATION: 'REQUEST_VERIFICATION',
  OPEN_VERIFICATION: 'OPEN_VERIFICATION',
  CLOSE_VERIFICATION: 'CLOSE_VERIFICATION',
  SUBMIT_DECISION: 'SUBMIT_DECISION',
  APPLY_CONSEQUENCES: 'APPLY_CONSEQUENCES',
  PROCESS_THREATS: 'PROCESS_THREATS',
  RESOLVE_INCIDENT: 'RESOLVE_INCIDENT',
  PURCHASE_UPGRADE: 'PURCHASE_UPGRADE',
  ADJUST_RESOURCE: 'ADJUST_RESOURCE',
  PAUSE_SESSION: 'PAUSE_SESSION',
  RESUME_SESSION: 'RESUME_SESSION',
  ABANDON_SESSION: 'ABANDON_SESSION',
} as const;

export type GameActionType = (typeof GAME_ACTIONS)[keyof typeof GAME_ACTIONS];

export const DECISION_TYPES = {
  APPROVE: 'approve',
  DENY: 'deny',
  FLAG: 'flag',
  REQUEST_VERIFICATION: 'request_verification',
  DEFER: 'defer',
} as const;

export type DecisionType = (typeof DECISION_TYPES)[keyof typeof DECISION_TYPES];

export const GAME_THREAT_TIERS = {
  LOW: 'low',
  GUARDED: 'guarded',
  ELEVATED: 'elevated',
  HIGH: 'high',
  SEVERE: 'severe',
} as const;

export type GameThreatTier = (typeof GAME_THREAT_TIERS)[keyof typeof GAME_THREAT_TIERS];

export const FACILITY_TIER_LEVELS = {
  OUTPOST: 'outpost',
  STATION: 'station',
  VAULT: 'vault',
  FORTRESS: 'fortress',
  CITADEL: 'citadel',
} as const;

export type FacilityTierLevel = (typeof FACILITY_TIER_LEVELS)[keyof typeof FACILITY_TIER_LEVELS];
