import type { UpgradeType, UpgradeDefinition } from '@the-dmz/shared';

export const UPGRADE_CATALOG: Record<UpgradeType, UpgradeDefinition> = {
  rack: {
    id: 'rack',
    category: 'capacity',
    name: 'Rack Expansion',
    description: 'Add additional rack units for server deployment',
    baseCost: 500,
    installationDays: 2,
    installationOverhead: 0.1,
    minTier: 'outpost',
    prerequisites: [],
    resourceDelta: { rackCapacity: 21 },
    maintenanceDelta: 0.02,
    opExPerDay: 5,
    threatSurfaceDelta: 0.02,
  },
  power: {
    id: 'power',
    category: 'capacity',
    name: 'Power Capacity',
    description: 'Increase available power capacity in kilowatts',
    baseCost: 750,
    installationDays: 3,
    installationOverhead: 0.1,
    minTier: 'outpost',
    prerequisites: [],
    resourceDelta: { powerCapacity: 5 },
    maintenanceDelta: 0.02,
    opExPerDay: 10,
    threatSurfaceDelta: 0.01,
  },
  cooling: {
    id: 'cooling',
    category: 'capacity',
    name: 'Cooling System',
    description: 'Increase cooling capacity in tons',
    baseCost: 1000,
    installationDays: 3,
    installationOverhead: 0.15,
    minTier: 'outpost',
    prerequisites: [],
    resourceDelta: { coolingCapacity: 2.5 },
    maintenanceDelta: 0.02,
    opExPerDay: 8,
    threatSurfaceDelta: 0.01,
  },
  bandwidth: {
    id: 'bandwidth',
    category: 'capacity',
    name: 'Bandwidth Upgrade',
    description: 'Increase network bandwidth capacity',
    baseCost: 600,
    installationDays: 2,
    installationOverhead: 0.1,
    minTier: 'outpost',
    prerequisites: [],
    resourceDelta: { bandwidthCapacity: 50 },
    maintenanceDelta: 0.01,
    opExPerDay: 5,
    threatSurfaceDelta: 0.03,
  },
  power_efficiency: {
    id: 'power_efficiency',
    category: 'efficiency',
    name: 'Power Efficiency',
    description: 'Reduce power consumption through efficient hardware',
    baseCost: 800,
    installationDays: 2,
    minTier: 'station',
    prerequisites: ['power'],
    resourceDelta: { powerUsage: -0.15, efficiencyMultiplier: 1.1 },
    maintenanceDelta: -0.03,
    opExPerDay: 3,
    threatSurfaceDelta: 0,
  },
  cooling_efficiency: {
    id: 'cooling_efficiency',
    category: 'efficiency',
    name: 'Cooling Efficiency',
    description: 'Improve cooling efficiency with better airflow',
    baseCost: 900,
    installationDays: 2,
    minTier: 'station',
    prerequisites: ['cooling'],
    resourceDelta: { coolingUsage: -0.15, efficiencyMultiplier: 1.1 },
    maintenanceDelta: -0.03,
    opExPerDay: 3,
    threatSurfaceDelta: 0,
  },
  bandwidth_efficiency: {
    id: 'bandwidth_efficiency',
    category: 'efficiency',
    name: 'Bandwidth Optimization',
    description: 'Optimize network usage through compression and caching',
    baseCost: 700,
    installationDays: 1,
    minTier: 'station',
    prerequisites: ['bandwidth'],
    resourceDelta: { bandwidthUsage: -0.2, efficiencyMultiplier: 1.15 },
    maintenanceDelta: -0.02,
    opExPerDay: 2,
    threatSurfaceDelta: 0,
  },
  firewall: {
    id: 'firewall',
    category: 'security',
    name: 'Enterprise Firewall',
    description: 'Block unauthorized network traffic at the perimeter',
    baseCost: 1200,
    installationDays: 3,
    minTier: 'outpost',
    prerequisites: [],
    resourceDelta: {},
    securityDelta: { breachProbabilityModifier: -0.15, detectionProbabilityModifier: 0.1 },
    maintenanceDelta: 0.02,
    opExPerDay: 15,
    threatSurfaceDelta: 0.02,
  },
  ids: {
    id: 'ids',
    category: 'security',
    name: 'Intrusion Detection System',
    description: 'Detect suspicious network activity and patterns',
    baseCost: 1000,
    installationDays: 2,
    minTier: 'outpost',
    prerequisites: [],
    resourceDelta: { powerUsage: 0.5 },
    securityDelta: { detectionProbabilityModifier: 0.2 },
    maintenanceDelta: 0.03,
    opExPerDay: 12,
    threatSurfaceDelta: 0.01,
  },
  ips: {
    id: 'ips',
    category: 'security',
    name: 'Intrusion Prevention System',
    description: 'Actively block detected threats in real-time',
    baseCost: 1500,
    installationDays: 3,
    minTier: 'station',
    prerequisites: ['ids'],
    resourceDelta: { powerUsage: 1, bandwidthUsage: -0.1 },
    securityDelta: { breachProbabilityModifier: -0.1, mitigationBonus: 0.25 },
    maintenanceDelta: 0.04,
    opExPerDay: 20,
    threatSurfaceDelta: 0.03,
  },
  siem: {
    id: 'siem',
    category: 'security',
    name: 'SIEM Platform',
    description: 'Centralized security monitoring and correlation',
    baseCost: 2000,
    installationDays: 4,
    minTier: 'vault',
    prerequisites: ['ids', 'firewall'],
    resourceDelta: { rackUsage: 4, powerUsage: 2, bandwidthUsage: 5 },
    securityDelta: { detectionProbabilityModifier: 0.3, threatVectorModifiers: { insider: -0.2 } },
    maintenanceDelta: 0.05,
    opExPerDay: 35,
    threatSurfaceDelta: 0.05,
  },
  edr: {
    id: 'edr',
    category: 'security',
    name: 'Endpoint Detection & Response',
    description: 'Monitor and respond to endpoint threats',
    baseCost: 1800,
    installationDays: 3,
    minTier: 'vault',
    prerequisites: ['ids'],
    resourceDelta: { powerUsage: 1.5 },
    securityDelta: {
      breachProbabilityModifier: -0.1,
      mitigationBonus: 0.2,
      threatVectorModifiers: { malware: -0.25 },
    },
    maintenanceDelta: 0.04,
    opExPerDay: 25,
    threatSurfaceDelta: 0.03,
  },
  waf: {
    id: 'waf',
    category: 'security',
    name: 'Web Application Firewall',
    description: 'Protect web applications from common attacks',
    baseCost: 1100,
    installationDays: 2,
    minTier: 'station',
    prerequisites: ['firewall'],
    resourceDelta: { bandwidthUsage: -0.05 },
    securityDelta: { breachProbabilityModifier: -0.12, threatVectorModifiers: { web: -0.3 } },
    maintenanceDelta: 0.03,
    opExPerDay: 18,
    threatSurfaceDelta: 0.02,
  },
  threat_intel_feed: {
    id: 'threat_intel_feed',
    category: 'security',
    name: 'Threat Intelligence Feed',
    description: 'Real-time threat indicators and IOC updates',
    baseCost: 800,
    installationDays: 1,
    minTier: 'station',
    prerequisites: [],
    resourceDelta: { bandwidthUsage: 1 },
    securityDelta: { detectionProbabilityModifier: 0.15 },
    maintenanceDelta: 0.01,
    opExPerDay: 10,
    threatSurfaceDelta: 0.01,
  },
  soar: {
    id: 'soar',
    category: 'security',
    name: 'Security Orchestration and Automation',
    description: 'Automate incident response workflows',
    baseCost: 2500,
    installationDays: 5,
    minTier: 'fortress',
    prerequisites: ['siem', 'edr'],
    resourceDelta: { rackUsage: 6, powerUsage: 3 },
    securityDelta: { mitigationBonus: 0.35 },
    maintenanceDelta: 0.06,
    opExPerDay: 40,
    threatSurfaceDelta: 0.04,
  },
  honeypots: {
    id: 'honeypots',
    category: 'security',
    name: 'Honeypot Network',
    description: 'Deceive attackers with decoy systems',
    baseCost: 600,
    installationDays: 2,
    minTier: 'station',
    prerequisites: [],
    resourceDelta: { rackUsage: 2, powerUsage: 0.5, bandwidthUsage: 2 },
    securityDelta: {
      detectionProbabilityModifier: 0.1,
      threatVectorModifiers: { reconnaissance: -0.2 },
    },
    maintenanceDelta: 0.02,
    opExPerDay: 8,
    threatSurfaceDelta: 0.03,
  },
  zero_trust_gateway: {
    id: 'zero_trust_gateway',
    category: 'security',
    name: 'Zero Trust Gateway',
    description: 'Implement zero-trust network architecture',
    baseCost: 2200,
    installationDays: 4,
    minTier: 'vault',
    prerequisites: ['firewall', 'waf'],
    resourceDelta: { bandwidthUsage: -0.1 },
    securityDelta: { breachProbabilityModifier: -0.2, mitigationBonus: 0.15 },
    maintenanceDelta: 0.05,
    opExPerDay: 30,
    threatSurfaceDelta: 0.04,
  },
  ai_anomaly_detection: {
    id: 'ai_anomaly_detection',
    category: 'security',
    name: 'AI Anomaly Detection',
    description: 'Machine learning based threat detection',
    baseCost: 3000,
    installationDays: 5,
    minTier: 'fortress',
    prerequisites: ['siem', 'ids'],
    resourceDelta: { rackUsage: 8, powerUsage: 4, bandwidthUsage: 10 },
    securityDelta: { detectionProbabilityModifier: 0.35, breachProbabilityModifier: -0.1 },
    maintenanceDelta: 0.07,
    opExPerDay: 50,
    threatSurfaceDelta: 0.06,
  },
  monitoring: {
    id: 'monitoring',
    category: 'operations',
    name: 'Enhanced Monitoring',
    description: 'Comprehensive facility monitoring and alerting',
    baseCost: 500,
    installationDays: 1,
    minTier: 'outpost',
    prerequisites: [],
    resourceDelta: { rackUsage: 1 },
    maintenanceDelta: -0.02,
    opExPerDay: 5,
    threatSurfaceDelta: 0.01,
  },
  maintenance_automation: {
    id: 'maintenance_automation',
    category: 'operations',
    name: 'Maintenance Automation',
    description: 'Automated scheduling and execution of maintenance tasks',
    baseCost: 900,
    installationDays: 2,
    minTier: 'station',
    prerequisites: ['monitoring'],
    resourceDelta: {},
    maintenanceDelta: -0.05,
    opExPerDay: 8,
    threatSurfaceDelta: 0.01,
  },
  redundancy: {
    id: 'redundancy',
    category: 'operations',
    name: 'System Redundancy',
    description: 'Add redundant systems for fault tolerance',
    baseCost: 1500,
    installationDays: 3,
    minTier: 'vault',
    prerequisites: ['power', 'cooling'],
    resourceDelta: { rackUsage: 10, powerUsage: 3, coolingUsage: 1.5 },
    maintenanceDelta: -0.04,
    opExPerDay: 20,
    threatSurfaceDelta: 0.02,
  },
  preventive_maintenance: {
    id: 'preventive_maintenance',
    category: 'maintenance',
    name: 'Preventive Maintenance Program',
    description: 'Regular maintenance to prevent equipment failure',
    baseCost: 400,
    installationDays: 1,
    minTier: 'outpost',
    prerequisites: [],
    resourceDelta: {},
    maintenanceDelta: -0.08,
    opExPerDay: 5,
    threatSurfaceDelta: 0,
  },
  rapid_repair: {
    id: 'rapid_repair',
    category: 'maintenance',
    name: 'Rapid Repair Systems',
    description: 'Quick-fix capabilities for faster recovery',
    baseCost: 700,
    installationDays: 2,
    minTier: 'station',
    prerequisites: [],
    resourceDelta: {},
    maintenanceDelta: -0.1,
    opExPerDay: 8,
    threatSurfaceDelta: 0,
  },
  diagnostics: {
    id: 'diagnostics',
    category: 'maintenance',
    name: 'Advanced Diagnostics',
    description: 'Predictive maintenance and failure analysis',
    baseCost: 1100,
    installationDays: 2,
    minTier: 'vault',
    prerequisites: ['monitoring'],
    resourceDelta: { rackUsage: 2 },
    securityDelta: { detectionProbabilityModifier: 0.05 },
    maintenanceDelta: -0.12,
    opExPerDay: 12,
    threatSurfaceDelta: 0.01,
  },
};
