import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  loginSchema,
  refreshTokenSchema,
  registerSchema,
} from "../src/schemas/auth.schema.js";
import {
  dateRangeSchema,
  paginationSchema,
} from "../src/schemas/common.schema.js";
import {
  healthResponseSchema,
  healthQuerySchema,
  readinessResponseSchema,
} from "../src/schemas/health.schema.js";
import { createJsonSchema } from "../src/schemas/json-schema.js";

const entries: Array<[string, Record<string, unknown>]> = [
  ["loginJsonSchema", createJsonSchema(loginSchema)],
  ["registerJsonSchema", createJsonSchema(registerSchema)],
  ["refreshTokenJsonSchema", createJsonSchema(refreshTokenSchema)],
  ["paginationJsonSchema", createJsonSchema(paginationSchema)],
  ["dateRangeJsonSchema", createJsonSchema(dateRangeSchema)],
  ["healthQueryJsonSchema", createJsonSchema(healthQuerySchema)],
  ["healthResponseJsonSchema", createJsonSchema(healthResponseSchema)],
  ["readinessResponseJsonSchema", createJsonSchema(readinessResponseSchema)],
];

const renderExport = (name: string, schema: Record<string, unknown>): string =>
  `export const ${name} = ${JSON.stringify(schema, null, 2)} as const;`;

const output = `// This file is auto-generated by scripts/generate-json-schemas.ts. Do not edit.\n\n${entries
  .map(([name, schema]) => renderExport(name, schema))
  .join("\n\n")}\n`;

const outputPath = fileURLToPath(
  new URL("../src/schemas/json-schemas.generated.ts", import.meta.url),
);

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output, "utf8");
