import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  loginSchema,
  refreshTokenSchema,
  registerSchema,
  loginResponseSchema,
  registerResponseSchema,
  refreshResponseSchema,
  userSchema,
  logoutResponseSchema,
  profileSchema,
  updateProfileSchema,
  meResponseSchema,
} from '../src/schemas/auth.schema.js';
import { dateRangeSchema, paginationSchema } from '../src/schemas/common.schema.js';
import {
  healthResponseSchema,
  healthQuerySchema,
  readinessResponseSchema,
} from '../src/schemas/health.schema.js';
import { apiErrorSchema, apiErrorEnvelopeSchema } from '../src/schemas/api-envelope.schema.js';
import { createJsonSchema } from '../src/schemas/json-schema.js';
import {
  effectStateSchema,
  themePreferencesSchema,
  accessibilityPreferencesSchema,
  userPreferencesSchema,
  preferenceSourceSchema,
  effectivePreferenceValueSchema,
  effectiveThemePreferencesSchema,
  effectiveAccessibilityPreferencesSchema,
  effectivePreferencesSchema,
  updatePreferencesSchema,
  policyLockedPreferencesSchema,
} from '../src/schemas/preferences.schema.js';
import {
  gameSessionBootstrapSchema,
  gameSessionBootstrapResponseSchema,
} from '../src/schemas/game-session.schema.js';
import {
  webauthnChallengeRequestSchema,
  webauthnChallengeResponseSchema,
  webauthnRegistrationRequestSchema,
  webauthnVerificationRequestSchema,
  webauthnCredentialsListResponseSchema,
  webauthnRegistrationResponseSchema,
  webauthnVerificationResponseSchema,
  mfaStatusResponseSchema,
} from '../src/schemas/mfa.schema.js';

const entries: Array<[string, Record<string, unknown>]> = [
  ['loginJsonSchema', createJsonSchema(loginSchema)],
  ['registerJsonSchema', createJsonSchema(registerSchema)],
  ['refreshTokenJsonSchema', createJsonSchema(refreshTokenSchema)],
  ['loginResponseJsonSchema', createJsonSchema(loginResponseSchema)],
  ['registerResponseJsonSchema', createJsonSchema(registerResponseSchema)],
  ['refreshResponseJsonSchema', createJsonSchema(refreshResponseSchema)],
  ['userJsonSchema', createJsonSchema(userSchema)],
  ['logoutResponseJsonSchema', createJsonSchema(logoutResponseSchema)],
  ['profileJsonSchema', createJsonSchema(profileSchema)],
  ['updateProfileJsonSchema', createJsonSchema(updateProfileSchema)],
  ['meResponseJsonSchema', createJsonSchema(meResponseSchema)],
  ['paginationJsonSchema', createJsonSchema(paginationSchema)],
  ['dateRangeJsonSchema', createJsonSchema(dateRangeSchema)],
  ['healthQueryJsonSchema', createJsonSchema(healthQuerySchema)],
  ['healthResponseJsonSchema', createJsonSchema(healthResponseSchema)],
  ['readinessResponseJsonSchema', createJsonSchema(readinessResponseSchema)],
  ['apiErrorJsonSchema', createJsonSchema(apiErrorSchema)],
  ['apiErrorEnvelopeJsonSchema', createJsonSchema(apiErrorEnvelopeSchema)],
  ['effectStateJsonSchema', createJsonSchema(effectStateSchema)],
  ['themePreferencesJsonSchema', createJsonSchema(themePreferencesSchema)],
  ['accessibilityPreferencesJsonSchema', createJsonSchema(accessibilityPreferencesSchema)],
  ['userPreferencesJsonSchema', createJsonSchema(userPreferencesSchema)],
  ['preferenceSourceJsonSchema', createJsonSchema(preferenceSourceSchema)],
  ['effectivePreferenceValueJsonSchema', createJsonSchema(effectivePreferenceValueSchema)],
  ['effectiveThemePreferencesJsonSchema', createJsonSchema(effectiveThemePreferencesSchema)],
  [
    'effectiveAccessibilityPreferencesJsonSchema',
    createJsonSchema(effectiveAccessibilityPreferencesSchema),
  ],
  ['effectivePreferencesJsonSchema', createJsonSchema(effectivePreferencesSchema)],
  ['updatePreferencesJsonSchema', createJsonSchema(updatePreferencesSchema)],
  ['policyLockedPreferencesJsonSchema', createJsonSchema(policyLockedPreferencesSchema)],
  ['gameSessionBootstrapJsonSchema', createJsonSchema(gameSessionBootstrapSchema)],
  ['gameSessionBootstrapResponseJsonSchema', createJsonSchema(gameSessionBootstrapResponseSchema)],
  ['webauthnChallengeRequestJsonSchema', createJsonSchema(webauthnChallengeRequestSchema)],
  ['webauthnChallengeResponseJsonSchema', createJsonSchema(webauthnChallengeResponseSchema)],
  ['webauthnRegistrationRequestJsonSchema', createJsonSchema(webauthnRegistrationRequestSchema)],
  ['webauthnVerificationRequestJsonSchema', createJsonSchema(webauthnVerificationRequestSchema)],
  [
    'webauthnCredentialsListResponseJsonSchema',
    createJsonSchema(webauthnCredentialsListResponseSchema),
  ],
  ['webauthnRegistrationResponseJsonSchema', createJsonSchema(webauthnRegistrationResponseSchema)],
  ['webauthnVerificationResponseJsonSchema', createJsonSchema(webauthnVerificationResponseSchema)],
  ['mfaStatusResponseJsonSchema', createJsonSchema(mfaStatusResponseSchema)],
];

const renderExport = (name: string, schema: Record<string, unknown>): string =>
  `export const ${name} = ${JSON.stringify(schema, null, 2)} as const;`;

const output = `// This file is auto-generated by scripts/generate-json-schemas.ts. Do not edit.\n\n${entries
  .map(([name, schema]) => renderExport(name, schema))
  .join('\n\n')}\n`;

const outputPath = fileURLToPath(
  new URL('../src/schemas/json-schemas.generated.ts', import.meta.url),
);

const prettier = await import('prettier');
const prettierConfig = await prettier.resolveConfig(outputPath);
const formatted = await prettier.format(output, {
  ...(prettierConfig ?? {}),
  parser: 'typescript',
});

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, formatted, 'utf8');
