import type { SchemaOwnershipManifest, SchemaOwnershipEntry } from './ownership.types.js';

const AUTH_SHARED_SOURCES = [
  '@the-dmz/shared/schemas',
  '@the-dmz/shared/auth',
  '@the-dmz/shared/constants',
];

export const SCHEMA_OWNERSHIP_MANIFEST: SchemaOwnershipManifest = {
  ownership: [
    {
      module: 'campaign',
      schemaNamespace: 'Campaign',
      ownedSchemas: [
        'campaignStatusEnum',
        'campaignTypeEnum',
        'recurrencePatternEnum',
        'contentTypeEnum',
        'enrollmentStatusEnum',
        'campaignCreateSchema',
        'campaignUpdateSchema',
        'campaignStatusUpdateSchema',
        'campaignAudienceSchema',
        'campaignContentSchema',
        'campaignEscalationSchema',
        'campaignListQuerySchema',
        'enrollUsersSchema',
        'enrollmentStatusUpdateSchema',
        'campaignIdParamJsonSchema',
        'contentIdParamJsonSchema',
        'templateIdParamJsonSchema',
        'enrollmentIdParamJsonSchema',
        'userIdParamJsonSchema',
        'campaignCreateBodyJsonSchema',
        'campaignUpdateBodyJsonSchema',
        'campaignStatusUpdateBodyJsonSchema',
        'campaignAudienceBodyJsonSchema',
        'campaignContentBodyJsonSchema',
        'campaignEscalationBodyJsonSchema',
        'campaignListQueryJsonSchema',
        'enrollUsersBodyJsonSchema',
        'enrollmentStatusUpdateBodyJsonSchema',
        'saveTemplateBodyJsonSchema',
        'createFromTemplateBodyJsonSchema',
        'campaignResponseJsonSchema',
        'campaignListResponseJsonSchema',
        'campaignDetailResponseJsonSchema',
        'audienceResponseJsonSchema',
        'contentResponseJsonSchema',
        'escalationResponseJsonSchema',
        'progressResponseJsonSchema',
        'enrollmentResponseJsonSchema',
        'eligibleUsersResponseJsonSchema',
        'throttleCheckResponseJsonSchema',
        'enrollmentStatusResponseJsonSchema',
        'templateListResponseJsonSchema',
        'templateResponseJsonSchema',
        'messageResponseJsonSchema',
      ],
      ownedComponents: [
        'CampaignCreateBody',
        'CampaignUpdateBody',
        'CampaignStatusUpdateBody',
        'CampaignAudienceBody',
        'CampaignContentBody',
        'CampaignEscalationBody',
        'CampaignListQuery',
        'EnrollUsersBody',
        'EnrollmentStatusBody',
        'CampaignParams',
        'ContentParams',
        'TemplateParams',
        'EnrollmentParams',
        'UserParams',
        'SaveTemplateBody',
        'CreateFromTemplateBody',
      ],
      componentPatterns: [
        '^Campaign',
        '^Enrollment',
        '^Audience',
        '^Content',
        '^Escalation',
        '^Template',
      ],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'auth',
      schemaNamespace: 'Auth',
      ownedSchemas: [
        'loginBodyJsonSchema',
        'registerBodyJsonSchema',
        'refreshBodyJsonSchema',
        'authResponseJsonSchema',
        'refreshResponseJsonSchema',
        'meResponseJsonSchema',
        'updateProfileBodyJsonSchema',
        'profileResponseJsonSchema',
        'webauthnChallengeRequestJsonSchema',
        'webauthnChallengeResponseJsonSchema',
        'webauthnRegistrationRequestJsonSchema',
        'webauthnRegistrationResponseJsonSchema',
        'webauthnVerificationRequestJsonSchema',
        'webauthnVerificationResponseJsonSchema',
        'mfaStatusResponseJsonSchema',
        'webauthnCredentialsListResponseJsonSchema',
        'mfaMethodJsonSchema',
        'mfaChallengeStateJsonSchema',
        'webauthnCredentialJsonSchema',
        'totpEnrollmentRequestJsonSchema',
        'totpEnrollmentResponseJsonSchema',
        'totpVerifyRequestJsonSchema',
        'totpVerifyResponseJsonSchema',
        'mfaVerifyRequestJsonSchema',
        'mfaVerifyResponseJsonSchema',
        'backupCodesResponseJsonSchema',
        'mfaEnrollmentStatusResponseJsonSchema',
        'mfaDisableRequestJsonSchema',
        'passwordResetRequestBodyJsonSchema',
        'passwordResetRequestResponseJsonSchema',
        'passwordChangeRequestBodyJsonSchema',
        'passwordChangeRequestResponseJsonSchema',
        'ssoProvidersResponseJsonSchema',
        'ssoLoginInitiateRequestJsonSchema',
        'ssoLoginInitiateResponseJsonSchema',
        'ssoSAMLMetadataResponseJsonSchema',
        'samlACSRequestJsonSchema',
        'oidcCallbackRequestJsonSchema',
        'samlLogoutCallbackRequestJsonSchema',
        'oidcLogoutCallbackRequestJsonSchema',
        'federatedRevocationResponseJsonSchema',
        'createApiKeyJsonSchema',
        'rotateApiKeyJsonSchema',
        'revokeApiKeyJsonSchema',
        'apiKeyResponseJsonSchema',
        'apiKeyListResponseJsonSchema',
        'apiKeyWithSecretJsonSchema',
      ],
      ownedComponents: [
        'AuthLoginResponse',
        'AuthRegisterResponse',
        'AuthRefreshResponse',
        'AuthMeResponse',
        'AuthProfileResponse',
        'AuthUpdateProfileRequest',
        'AuthUser',
        'AuthSession',
        'WebauthnChallengeRequest',
        'WebauthnChallengeResponse',
        'WebauthnRegistrationRequest',
        'WebauthnRegistrationResponse',
        'WebauthnVerificationRequest',
        'WebauthnVerificationResponse',
        'MfaStatusResponse',
        'WebauthnCredentialsListResponse',
        'MfaMethod',
        'MfaChallengeState',
        'WebauthnCredential',
      ],
      componentPatterns: ['^Auth', '^Webauthn', '^Mfa'],
      sharedSources: AUTH_SHARED_SOURCES,
      exemptions: [],
    },
    {
      module: 'game',
      schemaNamespace: 'Game',
      ownedSchemas: ['gameSessionBootstrapResponseJsonSchema'],
      ownedComponents: ['GameSessionBootstrapResponse', 'GameSession', 'GamePlayer', 'GameState'],
      componentPatterns: ['^Game'],
      sharedSources: ['@the-dmz/shared/schemas', '@the-dmz/shared/game'],
      exemptions: [],
    },
    {
      module: 'health',
      schemaNamespace: 'Health',
      ownedSchemas: [
        'healthQueryJsonSchema',
        'healthResponseJsonSchema',
        'readinessResponseJsonSchema',
      ],
      ownedComponents: ['HealthQuery', 'HealthResponse', 'ReadinessResponse'],
      componentPatterns: ['^Health', '^Readiness'],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'content',
      schemaNamespace: 'Content',
      ownedSchemas: [
        'emailTemplateListJsonSchema',
        'createEmailTemplateBodyJsonSchema',
        'emailTemplateJsonSchema',
        'emailTemplateListResponseJsonSchema',
        'emailTemplateResponseJsonSchema',
        'scenarioListQueryJsonSchema',
        'scenarioJsonSchema',
        'scenarioBeatJsonSchema',
        'scenarioWithBeatsJsonSchema',
        'scenarioListResponseJsonSchema',
        'scenarioResponseJsonSchema',
        'documentTemplateListQueryJsonSchema',
        'documentTemplateJsonSchema',
        'documentTemplateListResponseJsonSchema',
        'documentTemplateResponseJsonSchema',
        'localizedContentJsonSchema',
        'localizedContentResponseJsonSchema',
        'aiGenerationLogJsonSchema',
      ],
      ownedComponents: [
        'EmailTemplate',
        'Scenario',
        'ScenarioBeat',
        'ScenarioWithBeats',
        'DocumentTemplate',
        'LocalizedContent',
        'AiGenerationLog',
        'ThreatLevel',
        'Faction',
        'DocumentType',
      ],
      componentPatterns: [
        '^EmailTemplate',
        '^Scenario',
        '^DocumentTemplate',
        '^LocalizedContent',
        '^Content',
      ],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'aiPipeline',
      schemaNamespace: 'Ai',
      ownedSchemas: [
        'aiPromptTemplateJsonSchema',
        'aiPromptTemplateListQueryJsonSchema',
        'aiPromptTemplatePathParamsJsonSchema',
        'aiPromptTemplateCreateBodyJsonSchema',
        'aiPromptTemplateUpdateBodyJsonSchema',
        'aiPromptTemplateListResponseJsonSchema',
        'aiPromptTemplateResponseJsonSchema',
        'aiGenerationResponseJsonSchema',
        'aiEmailGenerationBodyJsonSchema',
        'aiIntelBriefGenerationBodyJsonSchema',
        'aiScenarioVariationGenerationBodyJsonSchema',
      ],
      ownedComponents: [
        'AiPromptTemplate',
        'AiPromptTemplateListResponse',
        'AiPromptTemplateResponse',
        'AiGenerationResponse',
        'AiEmailGenerationRequest',
        'AiIntelBriefGenerationRequest',
        'AiScenarioVariationGenerationRequest',
      ],
      componentPatterns: ['^Ai'],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'scim',
      schemaNamespace: 'Scim',
      ownedSchemas: [
        'scimUserSchema',
        'scimGroupSchema',
        'scimListResponseSchema',
        'scimBulkGetOperationSchema',
        'scimBulkPostOperationSchema',
        'scimBulkPutOperationSchema',
        'scimBulkPatchOperationSchema',
        'scimBulkDeleteOperationSchema',
        'scimBulkOperationSchema',
        'scimBulkRequestSchema',
        'scimBulkResponseSchema',
      ],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'webhooks',
      schemaNamespace: 'Webhooks',
      ownedSchemas: [],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'email',
      schemaNamespace: 'Email',
      ownedSchemas: [],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'narrative',
      schemaNamespace: 'Narrative',
      ownedSchemas: [],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'settings',
      schemaNamespace: 'Settings',
      ownedSchemas: [],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'analytics',
      schemaNamespace: 'Analytics',
      ownedSchemas: [],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'featureFlags',
      schemaNamespace: 'FeatureFlags',
      ownedSchemas: [
        'createFeatureFlagSchema',
        'updateFeatureFlagSchema',
        'tenantOverrideSchema',
        'featureFlagResponseSchema',
        'featureFlagListResponseSchema',
        'featureFlagWithOverrideResponseSchema',
        'activeFlagsResponseSchema',
      ],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'scorm',
      schemaNamespace: 'Scorm',
      ownedSchemas: [
        'createScormPackageSchema',
        'scormPackageResponseSchema',
        'createRegistrationSchema',
        'updateRegistrationSchema',
        'scormRegistrationResponseSchema',
      ],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'xapi',
      schemaNamespace: 'Xapi',
      ownedSchemas: [
        'xapiStatementInputSchema',
        'xapiArchiveInputSchema',
        'lrsConfigInputSchema',
        'lrsConfigUpdateSchema',
        'xapiActorInputSchema',
        'xapiVerbInputSchema',
        'xapiObjectDefinitionInputSchema',
        'xapiObjectInputSchema',
        'xapiScoreInputSchema',
        'xapiResultInputSchema',
        'xapiContextInputSchema',
        'xapiExtensionsSchema',
      ],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'billing',
      schemaNamespace: 'Billing',
      ownedSchemas: [],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'retention',
      schemaNamespace: 'Retention',
      ownedSchemas: [
        'createPolicyBodySchema',
        'updatePolicyBodySchema',
        'applyTemplateBodySchema',
        'listArchivesQuerySchema',
        'jobHistoryQuerySchema',
      ],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'achievements',
      schemaNamespace: 'Achievements',
      ownedSchemas: [],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'multiplayer',
      schemaNamespace: 'Multiplayer',
      ownedSchemas: [
        'partyStatusSchema',
        'difficultySchema',
        'declaredRoleSchema',
        'createPartySchema',
        'joinPartySchema',
        'setRoleSchema',
        'partyMemberResponseSchema',
        'partyResponseSchema',
        'createPartyResponseSchema',
      ],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
    {
      module: 'chat',
      schemaNamespace: 'Chat',
      ownedSchemas: [
        'channelTypeSchema',
        'sendMessageBodySchema',
        'sendMessageResponseSchema',
        'getMessagesQuerySchema',
        'chatMessageSchema',
        'getMessagesResponseSchema',
        'deleteMessageResponseSchema',
        'reportMessageBodySchema',
        'reportMessageResponseSchema',
        'chatChannelSchema',
        'listChannelsResponseSchema',
        'getChannelResponseSchema',
      ],
      ownedComponents: [],
      componentPatterns: [],
      sharedSources: ['@the-dmz/shared/schemas'],
      exemptions: [],
    },
  ],
};

export function getSchemaOwnership(moduleName: string): SchemaOwnershipEntry | undefined {
  return SCHEMA_OWNERSHIP_MANIFEST.ownership.find((o) => o.module === moduleName);
}

export function isSchemaOwnedByModule(moduleName: string, schemaName: string): boolean {
  const ownership = getSchemaOwnership(moduleName);
  if (!ownership) return false;
  return ownership.ownedSchemas.includes(schemaName);
}

export function isComponentOwnedByModule(moduleName: string, componentName: string): boolean {
  const ownership = getSchemaOwnership(moduleName);
  if (!ownership) return false;
  if (ownership.ownedComponents.includes(componentName)) return true;
  for (const pattern of ownership.componentPatterns) {
    const regex = new RegExp(pattern);
    if (regex.test(componentName)) return true;
  }
  return false;
}

export function isSharedSourceAllowed(moduleName: string, source: string): boolean {
  const ownership = getSchemaOwnership(moduleName);
  if (!ownership) return false;
  return ownership.sharedSources.some((s) => source.startsWith(s));
}

export function getSchemaOwner(schemaName: string): string | undefined {
  for (const ownership of SCHEMA_OWNERSHIP_MANIFEST.ownership) {
    if (ownership.ownedSchemas.includes(schemaName)) return ownership.module;
  }
  return undefined;
}

export function getComponentOwner(componentName: string): string | undefined {
  for (const ownership of SCHEMA_OWNERSHIP_MANIFEST.ownership) {
    if (ownership.ownedComponents.includes(componentName)) return ownership.module;
    for (const pattern of ownership.componentPatterns) {
      const regex = new RegExp(pattern);
      if (regex.test(componentName)) return ownership.module;
    }
  }
  return undefined;
}

export function isSchemaRegistered(schemaName: string): boolean {
  return getSchemaOwner(schemaName) !== undefined;
}

export function isComponentRegistered(componentName: string): boolean {
  return getComponentOwner(componentName) !== undefined;
}
